### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by joelviel** [Hashpack/hashconnect#92] opened 2022-04-07 15:54 UTC
blabla\node_modules\hashconnect\dist\main.js:1
export * from "./hashconnect";

**Comment by samuelnihoul** [comment] 2022-04-12 17:44
This can be quickfixed by renaming main.ts or main.js to main.mjs or main.mts

**Comment by samuelnihoul** [comment] 2022-04-12 19:04
This issue should be labelled as breaking

**Comment by joelviel** [comment] 2022-04-13 07:45
Indeed it is a blocking issue, can you fix it and make a stable release? I am trying to make a project for hedera22 hackathon.

**Comment by scalemaildev** [comment] 2022-04-15 15:54
I got around this by using NuxtJS's transpile feature in its config file. Depending on what framework you're using, you should have  some method of transpiling modules.

**Comment by TheMagnat** [comment] 2022-04-18 01:23
Same issue. I can't manage to make It work. I tried basic import from documentation and it give me the error.

**Comment by kkartunov** [comment] 2022-04-20 07:39
+1
Having same issue with NextJS. Here is error stack:
```
Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///home/kiril/dev/metasnap/meta-web/node_modules/hashconnect/dist/main.js (1)
...
```

**Comment by kkartunov** [comment] 2022-04-20 08:01
Actually it works with NextJS but one has to use https://www.npmjs.com/package/next-transpile-modules
Thanks for the tip @scalemaildev !

**Comment by samuelnihoul** [comment] 2022-04-20 13:27
actually for me it was not blocking, it was a random bug that went away by reversing last coming (and writing the same code again)

**Comment by samuelnihoul** [comment] 2022-04-24 19:07
@kkartunov , what does it do and how may i use it? 😊

**Comment by samuelnihoul** [comment] 2022-04-24 20:21
I assume it can transpile a node module into your source code but unsure

**Comment by samuelnihoul** [comment] 2022-04-24 20:29
I have tried the following:
`
import withTM from 'next-transpile-modules'
withTM(['hashconnect']);
import {HashConnect,HashConnectTypes,MessageTypes} from 'hashconnect'`

but it gives `the can't resolve fs error` in the browser, and `unexpected token 'export'` error in the terminal

**Comment by idrissyed7** [comment] 2022-06-02 21:34
@teacoat Do we know when this issue will be resolved? We are trying to use this package on a new Svelte-Kit project but couldn't move forward because of this bug.

**Comment by idrissyed7** [comment] 2022-06-02 21:34
@teacoat Do we know when this issue will be resolved? We are trying to use this package on a new Svelte-Kit project but couldn't move forward because of this bug.

**Comment by teacoat** [comment] 2022-06-30 01:43
> This can be quickfixed by renaming main.ts or main.js to main.mjs or main.mts

It looks like there is are some .mjs and .mts files in the dist already, 
![image](https://user-images.githubusercontent.com/3913019/176574515-73400f08-1404-4e9e-862e-97e9e3502e20.png)

Can you provide a project I can reproduce this in?

**Comment by pwoosam** [comment] 2022-08-11 01:42
Here is a sample project to reproduce the error.
https://github.com/pwoosam/hashconnect-ts-bug

After cloning, run:
1. `npm i`
2. `npm run start`

**Comment by pwoosam** [comment] 2022-08-11 03:31
As a work around, I can clone the repo and compile as a CommonJS module by setting these fields in tsconfig.json:
    "target": "ESNext",
    "module": "CommonJS",


There are some additional issues that require more modification to work in a node environment (non-browser).
Such as installing polyfills for WebSocket and localstorage. Also removing references to window from the sourcecode.

**Comment by sergioaiobuilders** [comment] 2022-08-25 12:40
@pwoosam Just tried your PR and it works great! @teacoat when will it be merged?

**Closed** 2022-09-09 22:10 UTC
Labels: bug

**Comment by mrVers** [comment] 2022-09-13 15:31
Seems this issue is still present as of `0.2.3`, getting the same error message.

**Comment by pwoosam** [comment] 2022-09-13 18:58
@mrVers did you try importing the cjs library?

`import { HashConnect } from 'hashconnect/dist/cjs/main';`

**Comment by mrVers** [comment] 2022-09-14 09:24
@pwoosam No luck. I'm trying this on a React/NextJS project.
Even if I try your simple project https://github.com/pwoosam/hashconnect-ts-bug with the latest `0.2.3.` I'm seeing the same issue.

**Comment by franfernandez20** [comment] 2023-02-06 08:00
Any news or resolution of this?  I am having this issue importing anything from the package.

**Comment by scalemaildev** [comment] 2024-02-08 18:45
Was playing around in my old repos and discovered this problem appears to now be fixed in Nuxt3 latest.
